import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { GoogleOAuthProvider } from '@react-oauth/google'

const inter = Inter({
	subsets: ['latin'], // Add more subsets if needed (e.g., "latin-ext", "cyrillic")
	variable: '--font-inter', // Define a CSS variable for easier usage
	display: 'swap' // Optional: Avoid font loading delays
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className={inter.variable}>
			<GoogleOAuthProvider clientId='482323581679-ho9ubqllfa4a2p5n4ph2s395h3p14qsi.apps.googleusercontent.com'>
				<body className={'font-sans antialiased'}>{children}</body>
			</GoogleOAuthProvider>
		</html>
	)
}
